spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Album
    username: postgres
    password: postdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
      show-sql: true
    open-in-view: false
server:
  port: 9090